version: '3.4'

services:
  proxy:
    build: ./proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
  nginx:
    build: ./nginx
    container_name: nginx-web
    restart: always
    ports:
      - "5000:5000"
  flask:
    build: ./flask
    container_name: flask-was
    restart: always
    environment:
      - APP_NAME=FlaskTest
    expose:
      - "8080"