version: "3.7"

services:
    flask:
        build: ./flask
        image: ds_flask:ver1.1.1
        container_name: flask
        restart: always
        environment:
            - APP_NAME=ds_app
        expose:
            - "8080"
        ports:
            - "8080:8080"

    nginx:
        build: ./nginx
        image: ds_nginx:ver1
        container_name: nginx
        restart: always
        ports:
            - "5000:5000"
    
    proxy:
        build: ./proxy
        image: ds_proxy:ver1
        container_name: proxy
        restart: always
        ports:
            - "80:80"